Error: Could not find contracts/AuthorizableLite.sol from any sources
    at /Users/sullof/Projects/tweedentity/authorizable/node_modules/truffle-resolver/index.js:76:23
    at /Users/sullof/Projects/tweedentity/authorizable/node_modules/async/internal/onlyOnce.js:12:16
    at next (/Users/sullof/Projects/tweedentity/authorizable/node_modules/async/whilst.js:68:18)
    at /Users/sullof/Projects/tweedentity/authorizable/node_modules/truffle-resolver/index.js:64:7
    at /Users/sullof/Projects/tweedentity/authorizable/node_modules/truffle-resolver/fs.js:85:5
    at /Users/sullof/Projects/tweedentity/authorizable/node_modules/async/internal/once.js:12:16
    at replenish (/Users/sullof/Projects/tweedentity/authorizable/node_modules/async/internal/eachOfLimit.js:61:25)
    at iterateeCallback (/Users/sullof/Projects/tweedentity/authorizable/node_modules/async/internal/eachOfLimit.js:50:17)
    at /Users/sullof/Projects/tweedentity/authorizable/node_modules/async/internal/onlyOnce.js:12:16
    at ReadFileContext.callback (/Users/sullof/Projects/tweedentity/authorizable/node_modules/truffle-resolver/fs.js:81:14) 'Error: Could not find contracts/AuthorizableLite.sol from any sources\n    at /Users/sullof/Projects/tweedentity/authorizable/node_modules/truffle-resolver/index.js:76:23\n    at /Users/sullof/Projects/tweedentity/authorizable/node_modules/async/internal/onlyOnce.js:12:16\n    at next (/Users/sullof/Projects/tweedentity/authorizable/node_modules/async/whilst.js:68:18)\n    at /Users/sullof/Projects/tweedentity/authorizable/node_modules/truffle-resolver/index.js:64:7\n    at /Users/sullof/Projects/tweedentity/authorizable/node_modules/truffle-resolver/fs.js:85:5\n    at /Users/sullof/Projects/tweedentity/authorizable/node_modules/async/internal/once.js:12:16\n    at replenish (/Users/sullof/Projects/tweedentity/authorizable/node_modules/async/internal/eachOfLimit.js:61:25)\n    at iterateeCallback (/Users/sullof/Projects/tweedentity/authorizable/node_modules/async/internal/eachOfLimit.js:50:17)\n    at /Users/sullof/Projects/tweedentity/authorizable/node_modules/async/internal/onlyOnce.js:12:16\n    at ReadFileContext.callback (/Users/sullof/Projects/tweedentity/authorizable/node_modules/truffle-resolver/fs.js:81:14)'
